name: Publish to JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push tags
      id-token: write # For Deno to authenticate with JSR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Extract version from deno.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' deno.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version is $VERSION"

      - name: Configure Git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Git tag
        run: |
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: Publish to JSR
        run: deno publish
