name: Publish to JSR

on:
  push:
    tags:
      - 'v*' # Triggers on version tags like v0.1.0

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # For Deno to authenticate with JSR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Publish to JSR
        run: deno publish
